<a href="https://colab.research.google.com/github/sap-tarshi-ghosh/python_/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pandas is a python library used for data analysis and data manipulation.
#it allows us to work with structured/tabular data similar to excel.

import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.2

### Series using 1-d data

In [ ]:
data = [10, 20, 30, 40]

s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

custom indexing (not that necessary for now)

In [ ]:
s = pd.Series(data, index=["a","b","c","d"])
print(s)

a    NaN
b    NaN
c    NaN
d    NaN
dtype: object

In [ ]:
data = {
    "Name": ["Amit","Riya","Rahul","Sneha","Arjun","Priya","Karan","Neha"],
    "Age": [20,21,22,21,23,22,20,21],
    "Department": ["CS","CS","IT","IT","CS","IT","CS","IT"],
    "Marks": [85,78,92,74,88,95,67,80],
    "StudyHours": [3,2,4,2,5,4,1,3]
}

df = pd.DataFrame(data)

df

    Name  Age Department  Marks  StudyHours
0   Amit   20         CS     85           3
1   Riya   21         CS     78           2
2  Rahul   22         IT     92           4
3  Sneha   21         IT     74           2
4  Arjun   23         CS     88           5
5  Priya   22         IT     95           4
6  Karan   20         CS     67           1
7   Neha   21         IT     80           3

In [ ]:
df.head()

    Name  Age Department  Marks  StudyHours
0   Amit   20         CS     85           3
1   Riya   21         CS     78           2
2  Rahul   22         IT     92           4
3  Sneha   21         IT     74           2
4  Arjun   23         CS     88           5

In [ ]:
df.tail()

    Name  Age Department  Marks  StudyHours
3  Sneha   21         IT     74           2
4  Arjun   23         CS     88           5
5  Priya   22         IT     95           4
6  Karan   20         CS     67           1
7   Neha   21         IT     80           3

In [ ]:
# (row, column)
df.shape

(8, 5)

In [ ]:
df.columns

Index(['Name', 'Age', 'Department', 'Marks', 'StudyHours'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         8 non-null      int64
 2   Department  8 non-null      object
 3   Marks       8 non-null      int64
 4   StudyHours  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

             Age      Marks  StudyHours
count   8.000000   8.000000    8.000000
mean   21.250000  82.375000    3.000000
std     1.035098   9.425459    1.309307
min    20.000000  67.000000    1.000000
25%    20.750000  77.000000    2.000000
50%    21.000000  82.500000    3.000000
75%    22.000000  89.000000    4.000000
max    23.000000  95.000000    5.000000

# Selecting columns

In [ ]:
df["Marks"]

0    85
1    78
2    92
3    74
4    88
5    95
6    67
7    80
Name: Marks, dtype: int64

In [ ]:
df[["Name", "Marks"]]

    Name  Marks
0   Amit     85
1   Riya     78
2  Rahul     92
3  Sneha     74
4  Arjun     88
5  Priya     95
6  Karan     67
7   Neha     80

# Selecting rows

In [ ]:
df.iloc[0]

Name          Amit
Age             20
Department      CS
Marks           85
StudyHours       3
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

   Name  Age Department  Marks  StudyHours
0  Amit   20         CS     85           3
1  Riya   21         CS     78           2

In [ ]:
df.loc[0:2]

    Name  Age Department  Marks  StudyHours
0   Amit   20         CS     85           3
1   Riya   21         CS     78           2
2  Rahul   22         IT     92           4

In [ ]:
df.loc[0, "Name"]

'Amit'

# Filtering data

In [ ]:
df[df["Marks"] > 80]

    Name  Age Department  Marks  StudyHours
0   Amit   20         CS     85           3
2  Rahul   22         IT     92           4
4  Arjun   23         CS     88           5
5  Priya   22         IT     95           4

In [ ]:
df[(df["Marks"] > 80) & (df["StudyHours"] > 3)]
#we can also use or '|' depending upon the usecase

    Name  Age Department  Marks  StudyHours
2  Rahul   22         IT     92           4
4  Arjun   23         CS     88           5
5  Priya   22         IT     95           4

# Creating new column

In [ ]:
df["Pass"] = df["Marks"] >= 80

df

    Name  Age Department  Marks  StudyHours   Pass
0   Amit   20         CS     85           3   True
1   Riya   21         CS     78           2  False
2  Rahul   22         IT     92           4   True
3  Sneha   21         IT     74           2  False
4  Arjun   23         CS     88           5   True
5  Priya   22         IT     95           4   True
6  Karan   20         CS     67           1  False
7   Neha   21         IT     80           3   True

# Groupby

In [ ]:
df

    Name  Age Department  Marks  StudyHours
0   Amit   20         CS     85           3
1   Riya   21         CS     78           2
2  Rahul   22         IT     92           4
3  Sneha   21         IT     74           2
4  Arjun   23         CS     88           5
5  Priya   22         IT     95           4
6  Karan   20         CS     67           1
7   Neha   21         IT     80           3

In [ ]:
#grouping the same department based on the mean value of their marks
df.groupby("Department")["Age"].mean()

Department
CS    21.0
IT    21.5
Name: Age, dtype: float64

In [ ]:
#sorting the values based on marks greater to lower
df.sort_values("Marks", ascending=False)

    Name  Age Department  Marks  StudyHours   Pass
5  Priya   22         IT     95           4   True
2  Rahul   22         IT     92           4   True
4  Arjun   23         CS     88           5   True
0   Amit   20         CS     85           3   True
7   Neha   21         IT     80           3   True
1   Riya   21         CS     78           2  False
3  Sneha   21         IT     74           2  False
6  Karan   20         CS     67           1  False